apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  #serviceAccountName: 
  containers:
  - name: test
    image: pear1798/pod_rbac_test:v1
    command: ["sleep"]
    args: ["10000000000"]
    ports:
    - containerPort: 8090
  #nodeName: kind-worker 
  restartPolicy: Always
