apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-demo
spec: 
  containers:
  - name: test
    image: pear1798/pod_rbac_test:v1
    command: ["sleep"]
    args: ["10000000000"]
