apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: 'standard'#'standard'#manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

