apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: "test1"
spec:
  type: NodePort
  selector:
    type: cancall
  ports:
    - port: 80
      targetPort: http-web-svc
      protocol: TCP
      #（默认：30000-32767）
      nodePort: 30007
