apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test1
  labels:
    type: cancall
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc
