apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    name: cpu_user
spec:
  #serviceAccountName: 
  containers:
  - name: test
    image: pear1798/pod_rbac_test:v1
    command: ["sleep"]
    args: ["10000000000"]
    ports:
    - containerPort: 8090
    
#select cpu use% high pod
#kubectl top pod -l name=cpu_user --sort-by=cpu -A


